Module4 task3
htmlacademy-nodejs/1874327-typoteka-3 pull request #12
Opened 2021-11-03 03:36 UTC by knighter1

2021-11-03 06:58 UTC, what1s1ove requested changes

2021-11-03 06:58 UTC, what1s1ove commented on package.json
> +        "axios": "^0.24.0",
все версии пакетов должны быть зафиксированы (через флаг **`-E`** -`npm i pino -E`)

2021-11-03 06:58 UTC, what1s1ove commented on src/express/api.js
> +{
```suggestion
class API {
```
в js так не пишут (исправь для всех методов тоже)

2021-11-03 06:58 UTC, what1s1ove commented on src/express/api.js
> +    async getArticles() {
```suggestion
   getArticles() {
```
если не используешь await внутри, тебе это не нужно. Но писать можно да, для наглядности. Если хочешь, то можешь везде исправить

2021-11-03 06:58 UTC, what1s1ove commented on src/express/routes/index.js
> +const api = require(`../api`).getAPI();
require должны быть только вверху модуля

2021-11-03 06:58 UTC, what1s1ove commented on src/service/data-service/CategoriesService.js
> +            if (acc.has(publication.category))
там где должны быть курли, они всегда должны быть

2021-11-03 06:58 UTC, what1s1ove commented on src/service/api/articles.js
> +        console.log(req.body);
```suggestion
```

2021-11-03 06:58 UTC, what1s1ove commented on src/express/routes/my.js
> +    articles.forEach(article => {
используй мап. старайся избегать изменений по ссылке

2021-11-03 06:59 UTC, what1s1ove requested changes
в целом гуд, но отвыкает от жавы и шарпа)
в ЖС другие правила)

2021-11-05 03:07 UTC, knighter1 commented on src/service/data-service/CategoriesService.js
> +            if (acc.has(publication.category))
Ничего не понял, кто такие курли? )
О чем здесь идет речь?

2021-11-05 03:13 UTC, knighter1 commented on src/express/routes/my.js
> +    articles.forEach(article => {
Исправил, а в чем принципиальная разница?

2021-11-05 03:13 UTC, knighter1 commented
По функционалу замечаний нет?

2021-11-05 06:27 UTC, what1s1ove commented on src/service/data-service/CategoriesService.js
> +            if (acc.has(publication.category))
```
if (condition) {
  // actions
}
```

2021-11-05 06:27 UTC, what1s1ove commented on src/express/routes/my.js
> +    articles.forEach(article => {
если можно не мутировать, то лучше не мутировать

2021-11-05 06:27 UTC, what1s1ove commented
> По функционалу замечаний нет?

не, нету. все гуд

2021-11-05 07:24 UTC, what1s1ove requested changes

2021-11-05 07:24 UTC, what1s1ove commented on src/express/routes/index.js
>  const indexRouter = new Router();
лучше обернуть инициализацию каждого роута (индекс, категории и тд) в отдельную функцию

2021-11-05 07:24 UTC, what1s1ove commented on src/service/utils.js
> +module.exports.getRandomInt = (min, max) => {
экспорты должны быть только в конце файла (во всех файлах)

2021-11-05 07:24 UTC, what1s1ove commented on src/express/routes/index.js
>  'use strict';
в `index` файлах не должно быть логики

2021-11-05 07:24 UTC, merged